# Generated by Django 6.1.1 on 2026-09-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='categories/', verbose_name='Иконка (для главной страницы)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='currency',
            field=models.CharField(blank=True, help_text='Показывается после цены, например: сом, ₽, $', max_length=10, verbose_name='Валюта'),
        ),
    ]
