# Generated by Django 6.1.1 on 2026-10-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('working_hours', models.CharField(blank=True, max_length=100, verbose_name='Часы работы')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('map_link', models.URLField(blank=True, help_text='Ссылка на Google Карты или 2ГИС. В приложении откройте точку на карте, нажмите «Поделиться» и скопируйте ссылку.', verbose_name='Ссылка на карту')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'ordering': ['order'],
            },
        ),
    ]
